name: budget
channels:
  - defaults
dependencies:
   - python=3.9.16
   - pandas
   - seaborn
   - matplotlib
   - numpy
   - regex
   - jellyfish
   - pytesseract
   - ipykernel
   - openpyxl
   - fpdf
   - pip
   - pip:
      - dataframe_image
      - ocrmypdf
