# how to update:
#   - increment python version in this file
#   - conda env update --file environment_budget.yml
name: budget
channels:
  - defaults
dependencies:
   - python=3.12     # python=3.9.16
   - pandas
   - seaborn
   - matplotlib
   - numpy
   - regex
   - jellyfish
   - f90nml
   - fpdf2           # from fdpf import FPDF
   #- pytesseract
   - ipykernel
   - openpyxl
   - pyinstaller
   - pip
   - pip:
      - dataframe_image
      - ocrmypdf
      - getpass4
